import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:mr_helper_security_analyzer/models/scan_result.dart';
import 'package:mr_helper_security_analyzer/models/security_finding.dart';

/// MR HELPER - Web Application Security Analyzer
/// Generates a shareable PDF security report from a [ScanResult].
class ReportPdfService {
  static const PdfColor _primary = PdfColor.fromInt(0xFF00A8CC);
  static const PdfColor _dark = PdfColor.fromInt(0xFF1A1A2E);
  static const PdfColor _muted = PdfColor.fromInt(0xFF666666);

  /// Build the PDF document bytes for the given scan.
  Future<Uint8List> buildPdf(ScanResult scan) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _header(scan),
        footer: (context) => _footer(context),
        build: (context) => [
          _scoreBlock(scan),
          pw.SizedBox(height: 16),
          _targetBlock(scan),
          pw.SizedBox(height: 16),
          _headersBlock(scan),
          pw.SizedBox(height: 16),
          if (scan.serverInfo.isNotEmpty || scan.certificate['checked'] == true)
            _serverBlock(scan),
          if (scan.serverInfo.isNotEmpty || scan.certificate['checked'] == true)
            pw.SizedBox(height: 16),
          _findingsBlock(scan),
        ],
      ),
    );

    return doc.save();
  }

  /// Generate and open the OS share sheet with the report PDF.
  Future<void> sharePdf(ScanResult scan) async {
    final bytes = await buildPdf(scan);
    final safeName = scan.displayUrl.replaceAll(RegExp(r'[^A-Za-z0-9]+'), '_');
    await Printing.sharePdf(
      bytes: bytes,
      filename: 'MRHELPER_Security_Report_$safeName.pdf',
    );
  }

  // --- Sections -------------------------------------------------------------

  pw.Widget _header(ScanResult scan) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      margin: const pw.EdgeInsets.only(bottom: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: _primary, width: 2)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('MR HELPER',
                  style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: _dark)),
              pw.Text('Web Security Analyzer',
                  style: const pw.TextStyle(fontSize: 9, color: _muted)),
            ],
          ),
          pw.Text('SECURITY REPORT',
              style: pw.TextStyle(
                  fontSize: 12,
                  fontWeight: pw.FontWeight.bold,
                  color: _primary)),
        ],
      ),
    );
  }

  pw.Widget _footer(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 8),
      child: pw.Text(
        'Page ${context.pageNumber} of ${context.pagesCount}  •  Generated by MR HELPER',
        style: const pw.TextStyle(fontSize: 8, color: _muted),
      ),
    );
  }

  pw.Widget _scoreBlock(ScanResult scan) {
    final color = _scoreColor(scan.score);
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          _statColumn('SCORE', '${scan.score}/100', color),
          _statColumn('GRADE', scan.grade, color),
          _statColumn('RISK', scan.risk, color),
          _statColumn(
              'HEADERS',
              '${scan.presentHeaderCount}/${scan.presentHeaderCount + scan.missingHeaderCount}',
              _dark),
        ],
      ),
    );
  }

  pw.Widget _statColumn(String label, String value, PdfColor color) {
    return pw.Column(
      children: [
        pw.Text(value,
            style: pw.TextStyle(
                fontSize: 16, fontWeight: pw.FontWeight.bold, color: color)),
        pw.SizedBox(height: 2),
        pw.Text(label, style: const pw.TextStyle(fontSize: 8, color: _muted)),
      ],
    );
  }

  pw.Widget _targetBlock(ScanResult scan) {
    return _card('TARGET INFORMATION', [
      _kv('URL', scan.url),
      _kv('Domain', scan.displayUrl),
      _kv('HTTPS', scan.https ? 'Enabled' : 'Disabled'),
      _kv('Scanned', scan.formattedDate),
    ]);
  }

  pw.Widget _headersBlock(ScanResult scan) {
    final names = <String, String>{
      'content-security-policy': 'Content-Security-Policy',
      'strict-transport-security': 'Strict-Transport-Security',
      'x-frame-options': 'X-Frame-Options',
      'x-content-type-options': 'X-Content-Type-Options',
      'referrer-policy': 'Referrer-Policy',
      'permissions-policy': 'Permissions-Policy',
    };
    return _card('SECURITY HEADERS', [
      for (final entry in names.entries)
        _kv(entry.value,
            (scan.headers[entry.key] ?? false) ? 'Present' : 'Missing',
            valueColor: (scan.headers[entry.key] ?? false)
                ? PdfColors.green700
                : PdfColors.red700),
    ]);
  }

  pw.Widget _serverBlock(ScanResult scan) {
    final cert = scan.certificate;
    return _card('SERVER & CERTIFICATE', [
      if (scan.serverInfo['server'] != null)
        _kv('Server', '${scan.serverInfo['server']}'),
      if (scan.serverInfo['poweredBy'] != null)
        _kv('Powered By', '${scan.serverInfo['poweredBy']}'),
      if (cert['checked'] == true)
        _kv('Certificate', cert['valid'] == true ? 'Valid' : 'Invalid',
            valueColor: cert['valid'] == true
                ? PdfColors.green700
                : PdfColors.red700),
      if (cert['issuer'] != null) _kv('Issuer', '${cert['issuer']}'),
      if (cert['daysRemaining'] != null)
        _kv('Expires in', '${cert['daysRemaining']} days'),
    ]);
  }

  pw.Widget _findingsBlock(ScanResult scan) {
    final findings = scan.sortedFindings;
    return _card('FINDINGS (${findings.length})', [
      if (findings.isEmpty)
        pw.Text('No security issues detected.',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.green700)),
      for (final f in findings) _findingRow(f),
    ]);
  }

  pw.Widget _findingRow(SecurityFinding f) {
    final color = _severityColor(f.severity);
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                padding:
                    const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 1),
                decoration: pw.BoxDecoration(
                  color: color,
                  borderRadius: pw.BorderRadius.circular(2),
                ),
                child: pw.Text(f.severity.label.toUpperCase(),
                    style: pw.TextStyle(
                        fontSize: 7,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.white)),
              ),
              pw.SizedBox(width: 6),
              pw.Expanded(
                child: pw.Text(f.title,
                    style: pw.TextStyle(
                        fontSize: 10, fontWeight: pw.FontWeight.bold)),
              ),
            ],
          ),
          pw.SizedBox(height: 2),
          pw.Text(f.description,
              style: const pw.TextStyle(fontSize: 9, color: _muted)),
          if (f.recommendation != null)
            pw.Text('-> ${f.recommendation}',
                style:
                    const pw.TextStyle(fontSize: 9, color: PdfColors.green800)),
        ],
      ),
    );
  }

  // --- Helpers --------------------------------------------------------------

  pw.Widget _card(String title, List<pw.Widget> children) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title,
              style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight: pw.FontWeight.bold,
                  color: _primary)),
          pw.SizedBox(height: 8),
          ...children,
        ],
      ),
    );
  }

  pw.Widget _kv(String key, String value, {PdfColor? valueColor}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 4),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(key,
                style: const pw.TextStyle(fontSize: 9, color: _muted)),
          ),
          pw.Expanded(
            child: pw.Text(value,
                style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: valueColor ?? _dark)),
          ),
        ],
      ),
    );
  }

  PdfColor _scoreColor(int score) {
    if (score >= 80) return PdfColors.green700;
    if (score >= 60) return PdfColors.orange700;
    if (score >= 40) return PdfColors.deepOrange700;
    return PdfColors.red700;
  }

  PdfColor _severityColor(FindingSeverity s) {
    switch (s) {
      case FindingSeverity.critical:
        return PdfColors.red700;
      case FindingSeverity.high:
        return PdfColors.deepOrange700;
      case FindingSeverity.medium:
        return PdfColors.orange700;
      case FindingSeverity.low:
        return PdfColors.blue700;
      case FindingSeverity.info:
        return PdfColors.grey600;
    }
  }
}
