// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfptj1XnufKNjLCj7qvNY9P4d0PPQxd_c',
    appId: '1:229150698335:web:a2cf061444023d401ce4ea',
    messagingSenderId: '229150698335',
    projectId: 'mr-helper-app',
    authDomain: 'mr-helper-app.firebaseapp.com',
    storageBucket: 'mr-helper-app.firebasestorage.app',
    measurementId: 'G-EH4CWE1FT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-8lihczGeP4ni7RjLvX3Kbg3AmqqT_r4',
    appId: '1:229150698335:android:4acfdea11dcbd1651ce4ea',
    messagingSenderId: '229150698335',
    projectId: 'mr-helper-app',
    storageBucket: 'mr-helper-app.firebasestorage.app',
  );
}
